### ISSUE TITLE
Structured (group) sparsity is applied but weights are pruned elementwise

### ISSUE THREAD

**Issue by xuanlinli17** [yanghr/DeepHoyer#1]
For structured pruning where group Hoyer regularizer is applied, in `cifar/cifar_prun_tune.py`, the pruning process seems to prune all the weights whose absolute value is less than a threshold, instead of following Wen et. al (2016) (https://arxiv.org/abs/1608.03665) where (I believe) an entire filter / channel is pruned. Is this behavior intended? If so, would like to know have you tried pruning the entire filter / channel? Thanks!

**Comment by yanghr** [comment]
Thanks for the inquiry! Please note that in both Wen et al. and this work, the structural sparsity is induced by the group-sparsity regularizer (group Lasso or group-HS), not by the pruning process. The group-sparsity regularizer will make each group of parameters to become close-to-zero simultaneously, than the whole group will be removed if we prune those close-to-zero elements to exact zero. In our work we group the weights along the dimension of channels and filters, therefore the pruning process will remove the entire channel or filter.
